### ISSUE TITLE
Unable to access Data Model and Data Dictionary Files through link specified on https://github.com/mosip/mosip-docs/wiki/MOSIP-Data-Model

### ISSUE THREAD

**Issue by hosurkrishnan** [mosip/mosip-docs#1]
Unable to access Data Model and Data Dictionary Files through link specified on https://github.com/mosip/mosip-docs/wiki/MOSIP-Data-Model

The links to file do not working.

**Comment by sadanandegowda** [comment]
Updated data model related artifacts with correct links.

**Comment by hosurkrishnan** [comment]
Yes, it indeed worked.  Thanks for fixing it.
